import Anthropic from "@anthropic-ai/sdk";
import { GeneratedCopy, GeneratedSite, OnboardingData, SectionEmphasis, ToneProfileId } from "./types";
import { TONE_PROFILES } from "./toneProfiles";

const COPY_FIELDS = [
  "heroHeadline",
  "heroSubheadline",
  "heroCta",
  "aboutHeading",
  "aboutBody",
  "servicesHeading",
  "servicesIntro",
  "galleryHeading",
  "galleryIntro",
  "contactHeading",
  "contactIntro",
  "footerNote",
] as const;

const TONE_OPTIONS = [...Object.keys(TONE_PROFILES), "unchanged"] as const;
const CHANGE_OPTIONS = ["increase", "decrease", "unchanged"] as const;
const MOTION_OPTIONS = ["none", "subtle", "unchanged"] as const;

export interface FeedbackPatch {
  toneProfile: ToneProfileId | "unchanged";
  colorPrimary: string;
  colorAccent: string;
  motion: "none" | "subtle" | "unchanged";
  galleryEmphasis: "increase" | "decrease" | "unchanged";
  servicesEmphasis: "increase" | "decrease" | "unchanged";
  aboutEmphasis: "increase" | "decrease" | "unchanged";
  copy: Record<(typeof COPY_FIELDS)[number], string>;
  summary: string[];
}

const APPLY_FEEDBACK_TOOL: Anthropic.Tool = {
  name: "apply_site_feedback",
  description:
    "Decide exactly what to change on this tradesperson's website in response to their feedback, and describe the changes.",
  input_schema: {
    type: "object",
    properties: {
      toneProfile: {
        type: "string",
        enum: [...TONE_OPTIONS],
        description: "A new overall tone/style profile, or 'unchanged' if the feedback doesn't call for one.",
      },
      colorPrimary: {
        type: "string",
        description: "A new primary color as a hex code (e.g. '#2f7ea3'), or the literal string 'unchanged'.",
      },
      colorAccent: {
        type: "string",
        description: "A new accent color as a hex code, or the literal string 'unchanged'.",
      },
      motion: {
        type: "string",
        enum: [...MOTION_OPTIONS],
        description: "Whether to turn scroll animations on ('subtle'), off ('none'), or leave as-is ('unchanged').",
      },
      galleryEmphasis: { type: "string", enum: [...CHANGE_OPTIONS], description: "Whether to give the gallery section more or less visual prominence." },
      servicesEmphasis: { type: "string", enum: [...CHANGE_OPTIONS], description: "Whether to give the services section more or less visual prominence." },
      aboutEmphasis: { type: "string", enum: [...CHANGE_OPTIONS], description: "Whether to give the about section more or less visual prominence." },
      copy: {
        type: "object",
        description:
          "Rewritten text for any specific copy field the feedback calls for. Set a field to the literal string 'unchanged' if it doesn't need to change. Only rewrite what the feedback actually asks about — don't rewrite unrelated fields.",
        properties: Object.fromEntries(
          COPY_FIELDS.map((field) => [field, { type: "string", description: `New text for ${field}, or 'unchanged'.` }])
        ),
        required: [...COPY_FIELDS],
        additionalProperties: false,
      },
      summary: {
        type: "array",
        items: { type: "string" },
        description:
          "One short sentence per change actually made, written for the site owner (e.g. 'Made the copy warmer and friendlier.'). Empty array if nothing matched the feedback.",
      },
    },
    required: ["toneProfile", "colorPrimary", "colorAccent", "motion", "galleryEmphasis", "servicesEmphasis", "aboutEmphasis", "copy", "summary"],
    additionalProperties: false,
  },
  strict: true,
};

function buildPrompt(
  onboarding: OnboardingData,
  currentTone: ToneProfileId,
  currentCopy: GeneratedCopy,
  currentEmphasis: SectionEmphasis,
  message: string
): string {
  const toneDescriptions = Object.values(TONE_PROFILES)
    .map((t) => `- ${t.id}: ${t.label} — ${t.description}`)
    .join("\n");

  return [
    `${onboarding.businessName} is a ${onboarding.trade} business's website generated by an automated tool.`,
    `Current tone profile: ${currentTone}.`,
    `Available tone profiles:`,
    toneDescriptions,
    ``,
    `Current section emphasis (higher = more prominent): gallery=${currentEmphasis.gallery}, services=${currentEmphasis.services}, about=${currentEmphasis.about}.`,
    ``,
    `Current copy on the site:`,
    ...COPY_FIELDS.map((field) => `- ${field}: "${currentCopy[field]}"`),
    ``,
    `The site owner just typed this feedback about their own site, in plain English:`,
    `"${message}"`,
    ``,
    `Decide what to actually change in response. Be conservative — only touch what the feedback clearly calls for, and set everything else to 'unchanged'. If they mention a specific color by name, convert it to a sensible hex code. If they ask to rewrite or shorten specific copy, rewrite only that field, keeping it grounded in the business's own details rather than becoming generic. UK English, plain text, no markdown or emoji.`,
  ].join("\n");
}

/**
 * Returns a structured patch describing what to change on the site in
 * response to free-text feedback, or null on any failure (no API key,
 * network error, malformed response) so callers can fall back to the
 * rule-based adjuster without breaking the feedback flow.
 */
export async function interpretFeedbackWithAI(
  onboarding: OnboardingData,
  generated: GeneratedSite,
  currentTone: ToneProfileId,
  message: string
): Promise<FeedbackPatch | null> {
  if (!process.env.ANTHROPIC_API_KEY) return null;

  try {
    const client = new Anthropic();
    const response = await client.messages.create({
      model: "claude-opus-5",
      max_tokens: 2000,
      tools: [APPLY_FEEDBACK_TOOL],
      tool_choice: { type: "tool", name: "apply_site_feedback" },
      messages: [
        { role: "user", content: buildPrompt(onboarding, currentTone, generated.copy, generated.emphasis, message) },
      ],
    });

    const toolUse = response.content.find(
      (block): block is Anthropic.ToolUseBlock => block.type === "tool_use"
    );
    if (!toolUse) return null;

    const input = toolUse.input as Record<string, unknown>;
    if (
      typeof input.toneProfile !== "string" ||
      typeof input.colorPrimary !== "string" ||
      typeof input.colorAccent !== "string" ||
      typeof input.motion !== "string" ||
      typeof input.galleryEmphasis !== "string" ||
      typeof input.servicesEmphasis !== "string" ||
      typeof input.aboutEmphasis !== "string" ||
      typeof input.copy !== "object" ||
      input.copy === null ||
      !Array.isArray(input.summary)
    ) {
      return null;
    }
    const copy = input.copy as Record<string, unknown>;
    for (const field of COPY_FIELDS) {
      if (typeof copy[field] !== "string") return null;
    }

    return input as unknown as FeedbackPatch;
  } catch (error) {
    console.error("AI feedback interpreter failed, falling back to rules:", error);
    return null;
  }
}
