import { StyleTokens, ToneProfileId } from "./types";

export const STYLE_TOKENS: Record<ToneProfileId, StyleTokens> = {
  friendly: {
    colorPrimary: "#e8734a",
    colorSecondary: "#fff4ec",
    colorAccent: "#2f8f6e",
    colorBackground: "#fffaf5",
    colorSurface: "#ffffff",
    colorText: "#2b2320",
    colorMuted: "#7a6c63",
    fontHeading: "var(--font-quicksand), sans-serif",
    fontBody: "var(--font-nunito), sans-serif",
    radius: "1.25rem",
    density: "cozy",
  },
  "no-nonsense": {
    colorPrimary: "#111318",
    colorSecondary: "#f4f4f5",
    colorAccent: "#d62828",
    colorBackground: "#ffffff",
    colorSurface: "#ffffff",
    colorText: "#111318",
    colorMuted: "#52525b",
    fontHeading: "var(--font-archivo), sans-serif",
    fontBody: "var(--font-inter), sans-serif",
    radius: "0.25rem",
    density: "compact",
  },
  premium: {
    colorPrimary: "#101828",
    colorSecondary: "#f5f0e6",
    colorAccent: "#b08d57",
    colorBackground: "#faf8f4",
    colorSurface: "#ffffff",
    colorText: "#151b26",
    colorMuted: "#5c6474",
    fontHeading: "var(--font-playfair), serif",
    fontBody: "var(--font-inter), sans-serif",
    radius: "0.5rem",
    density: "spacious",
  },
  approachable: {
    colorPrimary: "#2f7ea3",
    colorSecondary: "#eaf5f9",
    colorAccent: "#f2b134",
    colorBackground: "#f7fbfd",
    colorSurface: "#ffffff",
    colorText: "#1f2b33",
    colorMuted: "#5c7280",
    fontHeading: "var(--font-baloo), sans-serif",
    fontBody: "var(--font-mulish), sans-serif",
    radius: "1rem",
    density: "cozy",
  },
};
